-- Quick seed with comprehensive test data for The Shattered Accord campaign
-- Campaign ID: 1ceec234-523b-4e25-a0b5-097c71018be5

-- Delete in reverse dependency order
DELETE FROM creatures WHERE campaign_id = '1ceec234-523b-4e25-a0b5-097c71018be5';
DELETE FROM items WHERE campaign_id = '1ceec234-523b-4e25-a0b5-097c71018be5';
DELETE FROM custom_mechanics WHERE campaign_id = '1ceec234-523b-4e25-a0b5-097c71018be5';
DELETE FROM session_preps WHERE campaign_id = '1ceec234-523b-4e25-a0b5-097c71018be5';
DELETE FROM planar_forces WHERE campaign_id = '1ceec234-523b-4e25-a0b5-097c71018be5';
DELETE FROM world_rules WHERE campaign_id = '1ceec234-523b-4e25-a0b5-097c71018be5';
DELETE FROM lore_entries WHERE campaign_id = '1ceec234-523b-4e25-a0b5-097c71018be5';
DELETE FROM player_characters WHERE campaign_id = '1ceec234-523b-4e25-a0b5-097c71018be5';
DELETE FROM quests WHERE campaign_id = '1ceec234-523b-4e25-a0b5-097c71018be5';
DELETE FROM session_recaps WHERE campaign_id = '1ceec234-523b-4e25-a0b5-097c71018be5';
DELETE FROM npcs WHERE campaign_id = '1ceec234-523b-4e25-a0b5-097c71018be5';
DELETE FROM locations WHERE campaign_id = '1ceec234-523b-4e25-a0b5-097c71018be5';
DELETE FROM factions WHERE campaign_id = '1ceec234-523b-4e25-a0b5-097c71018be5';

-- ============================================================================
-- FACTIONS
-- ============================================================================
INSERT INTO factions (id, campaign_id, name, description, faction_type, power_level, goals, resources, dm_true_agenda, player_knowledge, tags, created_at, updated_at)
VALUES
('faction-accord', '1ceec234-523b-4e25-a0b5-097c71018be5', 'The Shattered Accord', 'Ancient coalition of mages who created the reality anchor network 500 years ago. Once unified under common purpose, now fractured by internal politics and the weight of their responsibility.', 'government', 'major', 'Maintain the reality anchors and prevent planar collapse at any cost', 'Reality anchor network, ancient arcane knowledge, political authority, mage towers across the city', 'One of the five Accord leaders is deliberately sabotaging the anchors, believing destruction and rebirth is the only path forward', 'common_knowledge', '["government","magic","fractured"]', 1700000000, 1700000000),

('faction-veil-walkers', '1ceec234-523b-4e25-a0b5-097c71018be5', 'Veil Walkers', 'Opportunistic smugglers and criminals who have learned to exploit the reality distortions for profit. They move contraband through unstable zones where law enforcement cannot follow.', 'criminal', 'moderate', 'Profit from the chaos and maintain their smuggling routes through distortion zones', 'Underground network, maps of distortion patterns, connections to black markets', 'Vex Shadowprice, their leader, has been secretly documenting distortion patterns and knows they point to deliberate sabotage. She is using this knowledge as leverage.', 'common_knowledge', '["criminal","smugglers","opportunistic"]', 1700000000, 1700000000),

('faction-truth-seekers', '1ceec234-523b-4e25-a0b5-097c71018be5', 'Truth Seekers', 'Scholars and researchers from the University who believe the Accord is hiding the true cause of the distortions. They seek to uncover ancient knowledge and expose any cover-ups.', 'academic', 'minor', 'Discover the truth about the distortions and share knowledge with the public', 'University resources, research archives, network of scholars', 'They are correct that the Accord is hiding information, but their public investigations are making it harder to catch the traitor quietly', 'common_knowledge', '["academic","researchers","idealistic"]', 1700000000, 1700000000);

-- ============================================================================
-- LOCATIONS
-- ============================================================================
INSERT INTO locations (id, campaign_id, name, description, location_type, population, cultural_characteristics, notable_npcs, factions_present, dm_secrets, player_knowledge, tags, created_at, updated_at)
VALUES
('loc-sanctum', '1ceec234-523b-4e25-a0b5-097c71018be5', 'The Accord Sanctum', 'A towering crystalline spire at the city center that houses the Accord leadership and the primary reality anchor. The building itself seems to bend light and space, with impossible geometry in its upper floors.', 'government', 200, 'Formal, hierarchical, intense focus on duty and tradition. Everyone speaks in hushed tones about the anchors as if discussing sacred artifacts.', '["npc-elara"]', '["faction-accord"]', 'The primary reality anchor deep beneath the Sanctum is failing faster than the others. Elara knows but has not told the full Accord council.', 'common_knowledge', '["magical","government","anchors"]', 1700000000, 1700000000),

('loc-veils-edge', '1ceec234-523b-4e25-a0b5-097c71018be5', 'Veils Edge District', 'A working-class neighborhood where reality has worn thin. Buildings sometimes flicker, sounds echo from impossible directions, and residents have learned to live with minor distortions as part of daily life.', 'residential', 5000, 'Resilient, suspicious of authority, dark humor about their situation. Strong sense of community born from shared hardship.', '["npc-vex","npc-rook"]', '["faction-veil-walkers"]', 'A stable portal to void space exists in the sewers beneath this district. The Veil Walkers have been using it for smuggling, not realizing it is slowly expanding.', 'common_knowledge', '["residential","distorted","dangerous"]', 1700000000, 1700000000),

('loc-university', '1ceec234-523b-4e25-a0b5-097c71018be5', 'The Twilight University', 'An ancient institution of magical learning with extensive archives. The building shifts between academic halls and mystical observatory depending on time of day.', 'academic', 800, 'Intellectual, competitive, obsessed with knowledge and discovery. Students and faculty both treat research as a form of warfare.', '["npc-seraph"]', '["faction-truth-seekers"]', 'The restricted archives contain the true history of the First Collapse, including the names of the Accord members who were responsible', 'common_knowledge', '["academic","magical","archives"]', 1700000000, 1700000000);

-- ============================================================================
-- NPCS
-- ============================================================================
INSERT INTO npcs (id, campaign_id, name, description, race, class, level, alignment, appearance, personality_traits, motivation, relationship_to_party, faction_id, dm_secrets, dm_plot_relevance, player_knowledge, tags, created_at, updated_at)
VALUES
('npc-elara', '1ceec234-523b-4e25-a0b5-097c71018be5', 'Magister Elara Duskweave', 'The pragmatic leader of the Shattered Accord who carries the burden of impossible choices. She knows more than she reveals and drinks tea obsessively to maintain her composure.', 'Half-Elf', '["Wizard","Diviner"]', 15, 'Lawful Neutral', 'Flowing silver robes embroidered with geometric runes, carries an ancient treaty scroll, perpetually tired eyes with dark circles, silver hair in elaborate braids', 'Methodical, burdened by secrets, diplomatic but will make ruthless decisions, drinks tea obsessively as a coping mechanism', 'Preserve the Accord and prevent planar collapse, even if it means sacrificing individuals for the greater good', 'quest giver and reluctant political ally', 'faction-accord', 'She knows which Accord member is causing the distortions (Magister Corvus) but fears civil war if she moves against him without proof. She is using the party as independent investigators.', 'Key NPC who will eventually reveal the traitor and ask the party to make an impossible choice: arrest him or let his plan complete', 'common_knowledge', '["quest-giver","faction-leader","diviner"]', 1700000000, 1700000000),

('npc-vex', '1ceec234-523b-4e25-a0b5-097c71018be5', 'Vex Shadowprice', 'A sharp-witted tiefling smuggler who treats information like currency. She is far more educated than she lets on and has been documenting the distortions with scientific precision.', 'Tiefling', '["Rogue"]', 10, NULL, 'Dark leather armor reinforced with void-metal, horns filed to sharp points, multiple hidden blade sheaths, carries journals filled with mathematical notations', 'Sarcastic, opportunistic, surprisingly well-read, values freedom above all, hides intelligence behind criminal persona', 'Profit and freedom - she wants to be rich enough to never owe anyone anything', 'information broker and reluctant ally', 'faction-veil-walkers', 'Her journals contain complete maps of distortion patterns that mathematically prove deliberate sabotage. She knows this information could start a war and is deciding who to sell it to.', 'Has the key evidence that proves the Accord traitor exists. Party must earn her trust or find another way to get her maps.', 'common_knowledge', '["merchant","faction-leader","rogue"]', 1700000000, 1700000000),

('npc-rook', '1ceec234-523b-4e25-a0b5-097c71018be5', 'Rook Ironvault', 'A dwarf paladin who lost his entire squad to a reality distortion. He has dedicated his life to protecting civilians in the distortion zones, even when the Accord writes areas off as lost.', 'Dwarf', '["Paladin"]', 8, 'Lawful Good', 'Battle-scarred plate armor with dents from impossible attacks, wields his squads ancestral warhammer, burn scars on his face from void energy', 'Direct, protective, uses dry humor to cope with trauma, deeply distrusts the Accord, will sacrifice himself for civilians', 'Protect civilians at any cost and find out why the Accord let his squad die', 'trusted ally and potential sacrifice', NULL, 'He witnessed the traitor at the site where his squad died but did not recognize them. Under the right circumstances, he could identify them.', 'Will provide military support in the final confrontation and may sacrifice himself to save the party', 'common_knowledge', '["investigator","ally","paladin"]', 1700000000, 1700000000),

('npc-seraph', '1ceec234-523b-4e25-a0b5-097c71018be5', 'Professor Seraph Moonwhisper', 'A brilliant but erratic eladrin researcher who has been piecing together the truth about the First Collapse. She leads the Truth Seekers and has no patience for politics.', 'Eladrin', '["Wizard"]', 12, 'Chaotic Good', 'Appearance shifts with fey seasons - currently autumn with copper hair and amber eyes, ink-stained fingers, multiple journals tucked into enchanted satchel', 'Brilliant, erratic, impatient with politics, obsessed with truth regardless of consequences, surprisingly kind to students', 'Uncover and publish the truth about the distortions, expose any Accord cover-ups', 'source of information and occasional complication', 'faction-truth-seekers', 'She has already discovered most of the truth and is preparing to publish it publicly, which will cause chaos. The party has a limited time to resolve things quietly.', 'Her research will force the final confrontation to happen sooner. She may become a target of the traitor.', 'common_knowledge', '["researcher","faction-leader","wizard"]', 1700000000, 1700000000);

-- ============================================================================
-- SESSION RECAPS
-- ============================================================================
INSERT INTO session_recaps (id, campaign_id, name, description, session_date, summary, key_events, player_decisions, dm_consequences, dm_behind_scenes, player_knowledge, tags, created_at, updated_at)
VALUES
('recap-01', '1ceec234-523b-4e25-a0b5-097c71018be5', 'The First Distortion', 'The party witnesses a reality distortion tear through the marketplace and meets Magister Elara who recruits them to investigate', 1700000000, 'Party was shopping in the marketplace when reality fractured. They fought distortion wraiths, saved civilians, and impressed Magister Elara enough that she recruited them to investigate the pattern of distortions.', '["Reality distortion tears through marketplace","Party defeats 2 Distortion Wraiths while protecting civilians","First meeting with Magister Elara at the scene","Elara offers party a contract to investigate distortion patterns","Discovery that reality anchors exist and are failing"]', '["Agreed to help the Accord investigate distortions","Chose to prioritize civilian rescue over pursuing fleeing wraith","Asked detailed questions about the anchors and their history"]', 'This distortion was deliberate - the traitor is testing the party to see if they are competent enough to be useful pawns or dangerous enough to eliminate', 'Elara deliberately arrived quickly because she had a divination that this would be where she found her investigators', 'common_knowledge', '["session-01","distortions","elara","combat"]', 1700000000, 1700000000),

('recap-02', '1ceec234-523b-4e25-a0b5-097c71018be5', 'Shadows and Secrets', 'Party infiltrates Veils Edge District, negotiates with Vex Shadowprice, and discovers smuggler maps showing distortion patterns', 1700100000, 'Following leads to Veils Edge, the party made contact with Vex and negotiated for her distortion maps. They avoided gang confrontation and discovered the patterns suggest intentional placement.', '["Entered Veils Edge District and observed reality distortions in daily life","First encounter with Veil Walkers gang","Negotiated with Vex Shadowprice - traded favor for information","Acquired maps showing mathematical patterns in distortion placement","Met Rook Ironvault who warned them about Accord secrets"]', '["Made deal with Vex instead of trying to intimidate or steal","Investigated sewers beneath the district","Avoided combat with Veil Walkers gang by being diplomatic"]', 'The maps reveal the traitor is moving between specific anchor sites. Vex knows this but has not told the party yet. The party is now being watched by both the traitor and the Accord.', 'Vex already knew the party was coming (she has informants in the Accord) and the maps she gave them are real but incomplete - she kept the most damning evidence', 'common_knowledge', '["session-02","veil-walkers","vex","investigation"]', 1700100000, 1700100000);

-- ============================================================================
-- QUESTS
-- ============================================================================
INSERT INTO quests (id, campaign_id, name, description, status, objectives, rewards, quest_giver_id, related_npcs, related_locations, started_session_id, dm_true_objective, dm_consequences, player_knowledge, tags, created_at, updated_at)
VALUES
('quest-investigate', '1ceec234-523b-4e25-a0b5-097c71018be5', 'Investigate the Distortion Pattern', 'Magister Elara has tasked the party with investigating the pattern of reality distortions across the city to identify their cause', 'in_progress', '["Map at least 5 distortion sites and document their characteristics","Identify common factors or patterns in distortion placement","Interview witnesses and survivors","Report findings to Magister Elara"]', '500 gold pieces, access to Accord resources and archives, political favor with the Accord', 'npc-elara', '["npc-elara","npc-vex","npc-rook"]', '["loc-sanctum","loc-veils-edge"]', 'recap-01', 'The true objective is to provide Elara with independent evidence of who the traitor is without alerting them. She cannot investigate directly without tipping her hand.', 'Success will force the traitor to accelerate their plans. Failure will result in more distortions and civilian casualties. The traitor is watching the party.', 'common_knowledge', '["main-quest","investigation","accord"]', 1700000000, 1700000000),

('quest-vex-maps', '1ceec234-523b-4e25-a0b5-097c71018be5', 'Acquire Vexs Maps', 'Vex Shadowprice has offered to sell her maps of distortion patterns in exchange for completing a favor and payment', 'completed', '["Complete favor for Vex (retrieve stolen shipment from rival gang)","Pay 200 gold pieces","Receive distortion pattern maps"]', 'Maps showing distortion patterns, Vex as a potential ongoing contact', 'npc-vex', '["npc-vex"]', '["loc-veils-edge"]', 'recap-02', 'The maps contain mathematical proof of deliberate sabotage, but Vex kept the pages that would identify the traitor. She is holding that information for leverage.', 'Party now has evidence that will make them targets. The traitor knows they have the maps. Vex is now invested in keeping the party alive because they are useful.', 'common_knowledge', '["completed","side-quest","veil-walkers"]', 1700100000, 1700100000);

-- ============================================================================
-- PLAYER CHARACTERS
-- ============================================================================
INSERT INTO player_characters (id, campaign_id, name, description, race, class, level, background, personality, goals, backstory, dm_secrets, dm_plot_threads, dm_true_motivation, dm_consequences, player_knowledge, tags, created_at, updated_at)
VALUES
('pc-aria', '1ceec234-523b-4e25-a0b5-097c71018be5', 'Aria Thornwilde', 'A human ranger searching for her missing sister, suspicious of authority and institutions', 'Human', '["Ranger"]', 5, 'Outlander', 'Observant, protective of nature and innocents, quiet until provoked, distrusts cities and politics', 'Find her missing sister who disappeared three years ago near a distortion zone', 'Grew up in the wilds with her sister. When distortions began affecting the forest, her sister went to investigate and never returned. Aria has been searching ever since.', 'Her sister Elena was taken by the Children of the Void cult and is still alive, but has been corrupted by void exposure. Elena is now a willing servant.', 'Arias search will eventually lead to the cult. She will have to choose between saving her sister or stopping the cult. Elena may have information about the traitor.', 'Find her sister at any cost, even if it means making dangerous deals or trusting the wrong people', 'If/when Aria finds her sister, she will face an impossible choice. Saving Elena might require sacrificing something catastrophic. Letting her go will break Aria.', 'common_knowledge', '["pc","ranger","outlander"]', 1700000000, 1700000000),

('pc-grimm', '1ceec234-523b-4e25-a0b5-097c71018be5', 'Grimm Ironforge', 'A dwarf cleric whose faith is being tested by divine silence during the crisis', 'Dwarf', '["Cleric"]', 5, 'Acolyte', 'Devout, stubborn, uses dark humor to cope, questions everything while maintaining faith', 'Restore his familys honor and understand why his god is silent during this crisis', 'From a long line of clerics. His family was disgraced when his grandfather was excommunicated for heresy (questioning divine will during a plague). Grimm became a cleric to restore the family name, but now finds himself asking the same questions.', 'Grimms patron deity is actually one of the Prismatic Court members (The Weaver). The god is not silent - it is deliberately testing Grimm to see if he will choose order over compassion.', 'The Weavers agenda (testing mortals through suffering) may directly conflict with Grimms desire to help people. He will eventually realize his god may be complicit in the distortions.', 'Serve his god faithfully and prove his devotion, but increasingly questioning divine silence and whether some rules should be broken to save lives', 'Grimm may lose his divine powers if he ultimately chooses to side with the party against The Weavers plans. He will have to choose between power and conscience.', 'common_knowledge', '["pc","cleric","acolyte"]', 1700000000, 1700000000);

-- ============================================================================
-- LORE ENTRIES
-- ============================================================================
INSERT INTO lore_entries (id, campaign_id, name, description, category, era_period, historical_accuracy, player_knowledge, tags, created_at, updated_at)
VALUES
('lore-binding', '1ceec234-523b-4e25-a0b5-097c71018be5', 'The Great Binding', 'The founding event where the Shattered Accord created the reality anchor network 500 years ago to prevent planar collapse', 'history', 'Age of Binding (500 years ago)', 'verified_by_multiple_sources', 'common_knowledge', '["history","accord","anchors","founding"]', 1700000000, 1700000000),

('lore-collapse', '1ceec234-523b-4e25-a0b5-097c71018be5', 'The First Collapse', 'A catastrophic event 50 years ago when a reality anchor failed in the eastern district, erasing 10,000 people from existence', 'history', 'Recent Past (50 years ago)', 'suppressed_by_authorities', 'dm_only', '["history","collapse","cover-up","tragedy"]', 1700000000, 1700000000);

-- ============================================================================
-- WORLD RULES
-- ============================================================================
INSERT INTO world_rules (id, campaign_id, name, description, rule_type, exceptions, player_knowledge, tags, created_at, updated_at)
VALUES
('rule-exposure', '1ceec234-523b-4e25-a0b5-097c71018be5', 'Distortion Exposure', 'Prolonged exposure to reality distortions causes cumulative mental and physical effects tracked by Distortion Points', 'environmental_hazard', 'Reality anchor fragments provide temporary immunity. Planar beings are immune.', 'common_knowledge', '["distortions","environmental","mechanical"]', 1700000000, 1700000000),

('rule-attunement', '1ceec234-523b-4e25-a0b5-097c71018be5', 'Reality Anchor Attunement', 'Spellcasters can attune to reality anchors for power at the cost of risking distortions', 'magic_system', 'Only spellcasters can attune. Maximum one anchor attunement at a time. Attunement broken if anchor is destroyed.', 'common_knowledge', '["magic","anchors","risk-reward"]', 1700000000, 1700000000);

-- ============================================================================
-- PLANAR FORCES
-- ============================================================================
INSERT INTO planar_forces (id, campaign_id, name, description, entity_type, domains, alignment, worshiper_base, plane_of_origin, dm_true_nature, player_knowledge, tags, created_at, updated_at)
VALUES
('planar-weaver', '1ceec234-523b-4e25-a0b5-097c71018be5', 'The Weaver', 'An ancient being of pure mathematics and geometry who maintains the fabric of reality through order and pattern', 'deity', '["Order","Pattern","Reality","Mathematics"]', 'Lawful Neutral', 'Scholars, architects, mathematicians, some members of the Accord', 'The Axiom (plane of perfect mathematical truth)', 'The Weaver created the distortions deliberately as a test. It believes reality should only persist if mortals prove worthy through suffering and problem-solving. It views compassion as weakness.', 'common_knowledge', '["deity","order","reality","test"]', 1700000000, 1700000000),

('planar-devourer', '1ceec234-523b-4e25-a0b5-097c71018be5', 'The Devourer Between', 'The hungering darkness between realities that seeks to unmake structured matter and return everything to primordial void', 'cosmic_entity', '["Void","Entropy","Hunger","Unmaking"]', 'Neutral Evil', 'Nihilists, void cults, those who have lost everything', 'The spaces between planes', 'The Devourer is not evil in a moral sense - it is entropy incarnate. It hungers to unmake reality the way a river flows downhill, as natural law rather than malicious choice. It cannot be reasoned with because it is a force, not a person.', 'common_knowledge', '["cosmic-horror","void","entropy","inevitable"]', 1700000000, 1700000000);

-- ============================================================================
-- SESSION PREP
-- ============================================================================
INSERT INTO session_preps (id, campaign_id, name, description, planned_date, status, planned_events, possible_encounters, plot_hooks, dm_notes, npcs_to_prep, locations_to_prep, player_knowledge, tags, created_at, updated_at)
VALUES
('prep-betrayal', '1ceec234-523b-4e25-a0b5-097c71018be5', 'The Accord Betrayal Revealed', 'Session where party confronts Elara with evidence and learns the identity of the traitor', 1700200000, 'ready', 'Party brings maps to Elara. She confirms their suspicions and reveals the traitor is Magister Corvus. Offers them a choice: help arrest him quietly or hear his side first. Corvus genuinely believes destroying the anchors and rebuilding is the only solution.', 'Social encounter with Elara (Insight vs Deception), Optional meeting with Corvus, Possible combat if party sides with Corvus, Chase through Sanctum if Corvus flees', 'Vex offers to sell the missing map pages; Rook reveals he saw someone at his squads death site; Professor Seraph is about to publish her findings', 'The betrayal reveal. Let players decide whether Corvus is wrong or if he has a point. No right answer. Stats for Corvus (CR 12 Wizard Abjurer) in case of combat. Elara will not help in combat - she will protect the Sanctum.', '["npc-elara"]', '["loc-sanctum"]', 'dm_only', '["prep","session-03","betrayal","choice"]', 1700200000, 1700200000);

-- ============================================================================
-- CUSTOM MECHANICS
-- ============================================================================
INSERT INTO custom_mechanics (id, campaign_id, name, description, mechanic_type, rules_text, prerequisites, source, player_knowledge, tags, created_at, updated_at)
VALUES
('mechanic-surge', '1ceec234-523b-4e25-a0b5-097c71018be5', 'Distortion Surge', 'Random reality warping effects that occur during combat in distortion zones, creating unpredictable tactical challenges', 'combat_environmental', 'At initiative count 20 (losing ties), roll 1d6 for random effect lasting until next surge: 1) Gravity reverses (DC 13 DEX save or fall to ceiling, taking fall damage), 2) Time hiccup (all combatants reroll initiative), 3) Duplicate ally appears (1d4 rounds, mirrors one random ally actions), 4) Weapons phase (all attacks have disadvantage as weapons pass through targets unpredictably), 5) Healing inverts to damage this round, 6) Random teleport (each combatant teleports 1d20x5 feet in random direction)', NULL, 'Homebrew environmental hazard for distortion zones', 'common_knowledge', '["combat","distortions","environmental","random"]', 1700000000, 1700000000);

-- ============================================================================
-- ITEMS
-- ============================================================================
INSERT INTO items (id, campaign_id, name, description, item_type, rarity, properties, owner_pc_id, dm_secret_properties, dm_true_nature, player_knowledge, tags, created_at, updated_at)
VALUES
('item-fragment', '1ceec234-523b-4e25-a0b5-097c71018be5', 'Fragment of the First Anchor', 'A palm-sized crystal that hums with stabilizing energy, a piece of the first reality anchor created during the Great Binding', 'wondrous_item', 'rare', 'Requires attunement. +1 to saves vs distortion effects. Can cast Dispel Magic once per day targeting distortion anomalies.', 'pc-aria', 'Contains a fragment of The Weavers consciousness that can telepathically communicate with the attuned user. Will offer guidance but with hidden agenda.', 'The Weaver can see through this item and is using it to observe the party. The guidance it offers will subtly push toward choices that further The Weavers test.', 'common_knowledge', '["magical","anchor","quest-reward","attunement"]', 1700000000, 1700000000),

('item-compass', '1ceec234-523b-4e25-a0b5-097c71018be5', 'Vexs Dimensional Compass', 'A strange brass compass that points toward areas of reality instability rather than magnetic north. Given to party by Vex after completing her quest.', 'wondrous_item', 'uncommon', 'Reveals direction and approximate distance (within 1 mile) to nearest distortion. Needle spins wildly when within 100 feet of active distortion.', 'pc-grimm', 'Also tracks reality anchor locations and displays their health status through subtle color changes in the brass (green=healthy, yellow=weakened, red=critical, black=destroyed)', 'Created by the traitor Magister Corvus and given to Vex. Contains a tracking enchantment that allows Corvus to know where the party is at all times.', 'common_knowledge', '["utility","navigation","tracking","veil-walkers"]', 1700000000, 1700000000);

-- ============================================================================
-- CREATURES
-- ============================================================================
INSERT INTO creatures (id, campaign_id, name, description, creature_type, challenge_rating, abilities, habitats, dm_behavior_notes, player_knowledge, tags, created_at, updated_at)
VALUES
('creature-wraith', '1ceec234-523b-4e25-a0b5-097c71018be5', 'Distortion Wraith', 'Translucent humanoid figure that flickers between existence, born from reality tears. Not truly undead but behaves similarly, drawn to stable matter like a moth to flame.', 'aberration', '3', '["Incorporeal Movement","Reality Distortion Aura (10ft radius, DC 13 WIS save or disadvantage on attacks)","Phase Strike (2d8 force damage, ignores armor)"]', '["Reality distortion zones","Failed anchor sites","Areas of planar instability"]', 'Mindlessly attracted to stable matter and life force. Prioritizes spellcasters because their magical energy registers as most solid to its senses. Will flee if reduced to 10 HP or less, phasing into the distortion.', 'common_knowledge', '["aberration","distortion","incorporeal","common"]', 1700000000, 1700000000),

('creature-cultist', '1ceec234-523b-4e25-a0b5-097c71018be5', 'Void-Touched Cultist', 'Former citizens who were corrupted by extended exposure to The Devourer Between. They retain intelligence but have abandoned their former lives in service to entropy.', 'humanoid', '2', '["Void Bolt (ranged spell attack +4, range 60ft, 2d6 necrotic damage)","Maddening Whispers (30ft, DC 12 WIS save or frightened)","Distortion Sense (can see invisible creatures and through illusions)"]', '["Veils Edge District sewers","Distortion zones","Cult hideouts near failing anchors"]', 'Follow cult hierarchy. Attempt to capture rather than kill potential converts. Can be reasoned with if party shows understanding of void philosophy or void-touched items. May provide information about cult plans if convinced party serves entropy.', 'common_knowledge', '["humanoid","cultist","corrupted","intelligent"]', 1700000000, 1700000000);
